### PR TITLE
d&i two methods for two functors

### PR DESCRIPTION
**Pull request by kamalsaleh**
IsomorphismFunctorFromQuiverRowsIntoAdditiveClosureOfAlgebroid and
IsomorphismFunctorFromAdditiveClosureOfAlgebroidIntoQuiverRows.

### CODE REVIEW

**Comment by kamalsaleh** [comment]
I will close this PR and move it to Freyd package in CAP.

**Comment by mohamed-barakat** [comment]
This will cause a dependency on `Bialgebroids` in  `FreydCategoriesForCAP` which would be unnecessary and probably undesirable. I would recommend reopening the PR here

**Comment by kamalsaleh** [comment]
That was why I made the PR here. But I can still provide them in FreydCategories package and make use of the `IsPackageMarkedForLoading` and `ValueGlobal`. I think, since the both equivalent categories are implemented their, It would make more sense, to include these operations in the `QuiverRows` documentation.

**Comment by mohamed-barakat** [comment]
I have no strong opinion. Please consult @sebastianpos.

**Comment by kamalsaleh** [comment]
@sebastianpos  I have created a branch `add_closure_quiver_rows_equivalence` in my CAP_Project fork https://github.com/kamalsaleh/CAP_project/

**Comment by sebastianpos** [comment]
I prefer not to have a dependency on `Bialgebroids` in `FreydCategoriesForCAP.`
I already had it once and created `QuiverRows` in order to free `FreydCategories` from this dependency.

**Comment by kamalsaleh** [comment]
@sebastianpos There will be no-dependency on Bialgebroids package. If the package is loaded the the functors are computable, otherwise an error will be raised mentioning that the Bialgebroids should be loaded with certain version as you can see in https://github.com/kamalsaleh/CAP_project/commits/add_closure_quiver_rows_equivalence.

**Pull request merged**
