### PR TITLE
d&i unitors and associators as functors

### PR DESCRIPTION
**Pull request by heiderich**

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
```
Syntax warning: Unbound global variable in /Users/mo/software/pkg/Bialgebroids/gap/Bialgebroids.gi:996
    iso_from_flat := IsomorphismFromFlatTensorProduct(algebra_of_A_BxC);
                                                     ^
Syntax warning: Unbound global variable in /Users/mo/software/pkg/Bialgebroids/gap/Bialgebroids.gi:1027
    iso_from_flat := IsomorphismFromFlatTensorProduct(algebra_of_AxB_C);
                                                     ^
```

**Comment by heiderich** [comment]
Is it possible that you are not using the latest QPA2 (https://github.com/oysteins/QPA2/commit/19f66d9e9781c63b642d8c47735894fdf4351154)?

**Comment by mohamed-barakat** [comment]
Yes, sorry, my mistake.

**Comment by mohamed-barakat** [comment]
Nice work, thank you very much.

**Pull request merged**
